sudo: false
language: clojure
lein: 2.7.1
jdk:
  - oraclejdk8

env:
  global:
    # Encrypted GITHUB_USER

    # Encrypted GITHUB_TOKEN
    - secure: "DyEoEUrxq3axPX6cX1zUqgdlcpXtA8YG56QuNWtFRtAIwYwyAe47owUQJrAFHFPNmuLUhAlQnC9Lb+MzkR187dsKLoNb4/mJP50PZdPqDAo1XYZIfZXQc6CXjq0UV4B1I2P2TKnur5QcIk5SaFuoePzqudyow1c0b8PHg9jLb6U5NPUs4bzVQ0ntuqok+5IiHKsS2xUUGn1jRYSYUZkEQDjya9XOFW+7hPbGaSb3n7c1a/CbsTeRW0mxHWxMwm8qMF7up9s+ApByqqWVnTng+ce+qYaoMNAQDHe+Sp3A7E2tnwK61qvlsbiYij8FP+MLURBijcrshcheDHikl5NhOZofrD0Bgx+PWtzyOeAcIZ38Ubqx6SYbYHkKnms+btRn0p7F+ClKDThebPcnFvlQWnUTLhVjXPQqIOBQOjOtmmE3eD2dAREcbre0mzLKObGa+IscZZ72rqtzSNyzDcgyqyzg/wYqw7POefGngI6y6qOsRHwrMRhAKx5A238KHgH4Wh3H1sgiwxsF7P0HGqmPGes9F65mzF3fV3el8HGsjE3oMYhViImyhiN37ONE1rDfuL6f0VGnZFDkV4zP7tySq+UKThjCkGmXhmrP2gHo6n8LDiA4tD0VMmSY4Hn8l8wbIYTlMMgVX5wisQ8Cy6vSZfBNcVR/WNpOoh4644W6isA="
    # Encrypted JIRA_USER

    # Encrypted JIRA_PASSWORD

    # Encrypted BITERGIA_USER

    # Encrypted BITERGIA_PASSWORD

    # Encrypted SMTP_USER

    # Encrypted SMTP_PASSWORD
    - ESCO_EMAIL_ADDRESS=peter@symphony.foundation

script: ./send-esco-reports.sh

notifications:
  webhooks: https://foundation.symphony.com/integration/v1/whi/simpleWebHookIntegration/58ae440fe4b0d18517ab5177/58af9f79e4b0d18517ab51a9
